### ISSUE TITLE
iOS touch

### ISSUE THREAD

**Issue by Joshfindit** [ttsiodras/ReactJS-Score4#1]
The game does not react to touch.

**Comment by ttsiodras** [comment]
Hi Josh - thanks for reporting it. Note that the game works fine on Android phones (and tablets) - apparently they translate taps to clicks (I just use `onClick` currently).

I'll see what I can do.

**Comment by ttsiodras** [comment]
Googling around, it seems that Safari carries this "feature" as a distinguished bug for years...  Apart from the obvious suggestions (e.g. install Chrome) some devs reported success by adding the "cursor: pointer" style to the clickable HTML element. 

I just added this workaround - can you check if it works now? Click [here](http://users.softlab.ntua.gr/~ttsiod/score4jsreact.html) for a rapid test - I don't have an iOS device, so no idea if this satisfies Safari or not.

**Comment by ttsiodras** [comment]
Dug up an ancient 3GS - it works under Safari now :-)

Closing,

**Comment by Joshfindit** [comment]
Yes, confirmed that it works on IPad and iPhone.
Cheers
